WITH F AS (
    SELECT *
    FROM RELATIVE_DATES
    WHERE
        WEEK_OFFSET BETWEEN -2 AND -1
        AND WEEK_COMPLETED = 1
)

SELECT C.*
FROM RELATIVE_DATES AS C
INNER JOIN F ON
    C.WEEKOFYEAR = F.WEEKOFYEAR
    AND C.DAYOFWEEK = F.DAYOFWEEK
    AND YEAR(F.DATE) - 1 = C.YEAR
