
version: 2

models:
  - name: dates
    description: "Base date spine for calendar"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: date
        tests:
          - unique
          - not_null
      - name: year
        tests:
          - not_null
      - name: quarter
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]
      - name: month
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: week
        tests:
          - not_null
      - name: dayofyear
        tests:
          - not_null
      - name: dayofmonth
        tests:
          - not_null
      - name: dayofweek
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]
      - name: isodayofweek
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7]
      - name: isoyear
        tests:
          - not_null
      - name: yearweek
        tests:
          - not_null
    tests:
      - expect_consecutive_dates:
          column_name: date
      - expect_no_gaps_in_dates:
          column_name: date

  - name: relative_dates
    description: "Relative dates with offsets and flags"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: date
        tests:
          - not_null
      - name: year_offset
        tests:
          - not_null
      - name: quarter_offset
        tests:
          - not_null
      - name: month_offset
        tests:
          - not_null
      - name: week_offset
        tests:
          - not_null
      - name: day_offset
        tests:
          - not_null
      - name: is_now
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: is_past
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: is_future
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
