SELECT
    Y.YEAR AS CURRENT_YEAR,
    Y.MONTH AS CURRENT_MONTH,
    Y.YEAR_START AS YEARSTART,
    Y.YEAR_END AS YEAREND,
    Y.MONTH_START AS MONTHSTART,
    Y.MONTH_END AS MONTHEND,
    Y.YEAR_START AS YTD_START,
    Y.MONTH_END AS YTD_END,
    YEAR(Y.MONTH_START + TO_MONTHS(1)) AS REPORT_YEAR,
    MONTH(Y.MONTH_START + TO_MONTHS(1)) AS REPORT_MONTH,
    Y.MONTH_START + TO_MONTHS(1) AS REPORT_DATE,
    Y.YEAR - 1 AS PRIOR_YEAR,
    Y.MONTH_START - TO_MONTHS(-1) AS PRIOR_MONTH,
    1 + DATEDIFF('DAY', Y.YEAR_START, Y.MONTH_END) AS YTD_DAYS,
    Y.YEAR_START - TO_YEARS(-1) AS PRIOR_YEAR_START,
    Y.MONTH_END - TO_YEARS(-1) AS PRIOR_YTD_END,
    Y.YEAR_END - TO_YEARS(-1) AS PRIOR_YEAR_END,
    Y.MONTH_START - TO_YEARS(-1) AS Y1_ROLLING_START,
    Y.MONTH_START - TO_YEARS(-2) AS Y2_ROLLING_START,
    Y.MONTH_START - TO_YEARS(-3) AS Y3_ROLLING_START,
    Y.MONTH_START - TO_YEARS(-4) AS Y4_ROLLING_START,
    Y.MONTH_START - TO_YEARS(-5) AS Y5_ROLLING_START
FROM (
    SELECT
        D.YEAR,
        D.MONTH,
        D.YEAR_START,
        D.YEAR_END,
        D.MONTH_START,
        D.MONTH_END
    FROM {{ ref('relative_dates') }} AS D
    GROUP BY
        D.YEAR, D.MONTH, D.YEAR_START, D.YEAR_END, D.MONTH_START, D.MONTH_END
) AS Y
